name: HanguTTS
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "15.0"

# external packages
packages:
  AWSiOSSDK:
    url: https://github.com/aws-amplify/aws-sdk-ios-spm.git
    from: 2.31.0        # any 2.30+ is fine

targets:
  # 1️⃣ Your framework target with AWS dependencies
  HanguCore:
    type: framework
    platform: iOS
    sources: [HanguCore]
    dependencies:
      - package: AWSiOSSDK
        product: AWSCore
      - package: AWSiOSSDK
        product: AWSPolly

  # 2️⃣ Your app target that links the local framework
  HanguTTS:
    type: application
    platform: iOS
    sources: [HanguTTS]
    dependencies:
      - target: HanguCore          # <-- changed from “package” to “target”
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: HanguTTS
        CFBundleIdentifier: com.example.hangutts
        UILaunchStoryboardName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
