name: Build iOS IPA

on:
  workflow_dispatch:      # manual trigger in GitHub UI

jobs:
  build:
    runs-on: macos-14     # free GitHub-hosted Sonoma runner
    steps:
      - uses: actions/checkout@v4

      # Build unsigned .app (skip code-signing)
      - name: Build app
        working-directory: ios          # <-- new line
        run: |
          xcodebuild \
            -scheme HanguTTS \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO

      # Package into an unsigned .ipa
      - name: Package IPA
        working-directory: ios          # stay in the ios folder
        run: |
          APP_PATH=$(find build/Build/Products/Release-iphoneos -name 'HanguTTS.app' | head -n 1)
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -r HanguTTS-unsigned.ipa Payload


      # Upload artifact for download
      - uses: actions/upload-artifact@v4
        with:
          name: HanguTTS-unsigned
          path: ios/HanguTTS-unsigned.ipa
