name: Build iOS IPA

on:
  workflow_dispatch:      # manual trigger in GitHub UI

jobs:
  build:
    runs-on: macos-14     # free GitHub-hosted Sonoma runner
    steps:
      - uses: actions/checkout@v4

      # Build unsigned .app (skip code-signing)
      - name: Build app
        working-directory: ios          # <-- new line
        run: |
          xcodebuild \
            -scheme HanguTTS \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO

      # Package into an unsigned .ipa
      - name: Package IPA
        run: |
          mkdir Payload
          cp -R build/Release-iphoneos/HanguTTS.app Payload/
          /usr/bin/xcrun -sdk iphoneos PackageApplication -v Payload -o HanguTTS-unsigned.ipa

      # Upload artifact for download
      - uses: actions/upload-artifact@v4
        with:
          name: HanguTTS-unsigned
          path: HanguTTS-unsigned.ipa
