name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      # 👉 NEW: generate the Xcode project
      - name: Generate Xcode project
        working-directory: ios
        run: |
          brew install xcodegen
          xcodegen generate

      # build unsigned .app
      - name: Build app
        working-directory: ios
        run: |
          xcodebuild \
            -scheme HanguTTS \
            -project HanguTTS.xcodeproj \   # ← now points at the generated project
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO

      # package into an unsigned .ipa
      - name: Package IPA
        working-directory: ios
        run: |
          APP_PATH=$(find build/Build/Products/Release-iphoneos -name 'HanguTTS.app' | head -n 1)
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -r HanguTTS-unsigned.ipa Payload

      # upload
      - uses: actions/upload-artifact@v4
        with:
          name: HanguTTS-unsigned
          path: HanguTTS-unsigned.ipa
